version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: DA
    restart: no
    ports:
      - "5431:5432"
    environment:
      POSTGRES_PASSWORD: "123456"
      PGDATA: "/var/lib/postgresql/18/docker"
    volumes:
      - db_data:/var/lib/postgresql
    networks:
      - default

volumes:
  db_data:
    external: true
    name: 964b639b173ce8503c6700b0ce4a4e4b18ce76573beb0cc4e594795f555229ef

networks:
  default:
    external: false
